# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('best_time', '0002_besttime_full_attend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialAttendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('best_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_attend', to='best_time.BestTime')),
            ],
        ),
    ]
