# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='free_time',
            new_name='FreeTime',
        ),
    ]
