# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('best_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='besttime',
            name='full_attend',
            field=models.ManyToManyField(related_name='fully_attend_time', to=settings.AUTH_USER_MODEL),
        ),
    ]
