# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('best_start_time', models.DateTimeField()),
                ('best_end_time', models.DateTimeField()),
                ('min_time_required', models.DateTimeField()),
                ('users', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
