# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20171104_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='users',
            new_name='members',
        ),
    ]
