# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20171104_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
