# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20171105_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='best_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='best_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
