# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_auto_20171105_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='min_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='time_span_max',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='time_span_min',
            field=models.DateTimeField(null=True),
        ),
    ]
