# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_auto_20171115_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='best_end_time',
            new_name='time_span_end',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='best_start_time',
            new_name='time_span_start',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time_span_max',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time_span_min',
        ),
    ]
