# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_auto_20171115_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='min_members',
            field=models.IntegerField(default=1),
        ),
    ]
