# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:06
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_auto_20171126_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='place',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='place_id',
        ),
        migrations.AddField(
            model_name='room',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
