# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_auto_20171126_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='place_id',
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
