# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_auto_20171129_1221'),
        ('room', '0019_auto_20171128_1038'),
    ]

    operations = [
    ]
