# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_auto_20171126_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='place_name',
            new_name='place',
        ),
    ]
