# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_room_hashid'),
        ('room', '0021_merge_20171129_1330'),
    ]

    operations = [
    ]
