# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_auto_20171203_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='anonymity',
            field=models.BooleanField(default=False),
        ),
    ]
