# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0024_room_anonymity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='best_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
